language: sh

sudo: required

branches:
  only:
    - master
    
before_install
  -sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  -sudo apt-get update
  -sudo apt-get install gcc-5 g++-5 gfortran-5

install:
  - make all
      
script:

after_script:
