language: sh

sudo: required

branches:
  only:
    - master

services:
  - docker
    
before_install

before_install:
  - docker pull cmbant/cosmobox

install:
  - docker run -v cmbant/cosmobox /bin/make -c "all"
      
script:

after_script:
