language: 
  sh
  python

python:
  - "2.7"

sudo: required

branches:
  only:
    - master

cache: apt

services:
  - docker
    
before_install:
  - docker pull mraveri/cosmicfishbowl

install:
  - sudo pip install coveralls

script: 
  - while true; do echo 'Travis do not sleep!'; sleep 300s; done &
  - TIME_PID=$! 
  - docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make python_test"
  - kill $TIME_PID

after_success: 
  - coveralls debug
  - coveralls
