language: 
  sh

sudo: required

branches:
  only:
    - master

cache: apt

services:
  - docker
    
before_install:
  - docker pull mraveri/cosmicfishbowl

script: 
  - while true; do echo 'Travis do not sleep!'; sleep 300s; done &
  - TIME_PID=$! 
  - docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make apps"
  - docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make test"
  - docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make documentation"
  - docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make examples"
  - docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make run_test"
  - kill $TIME_PID
