language: 
  sh

sudo: required

branches:
  only:
    - master

services:
  - docker
    
before_install:
  - docker pull mraveri/cosmicfishbowl

script:
  - docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make all"
