language: 
  sh

sudo: required

branches:
  only:
    - master

cache: apt

services:
  - docker
    
before_install:
  - sudo apt-get install -y maven
  - docker pull mraveri/cosmicfishbowl

script: 
  - travis_wait 30 mvn docker run -v $(pwd):/cosmicfish -t mraveri/cosmicfishbowl /bin/sh -c "cd cosmicfish ; make all"
